### ISSUE TITLE
Umlaut bug

### ISSUE THREAD

**Issue by jannehukka** [MartinSGill/TodoTxtJs#77]
Hi Martin,

and thanks for your great TodoTxtJs! 

I've noticed that the filtering doesn't work if the context name or project name includes letters with umlauts (Scandinavian/German/Finno-Ugric Ä,Ö etc.). Is there any chance you could take a look at that?

Best wishes,

Janne

**Comment by MartinSGill** [comment]
Hi Janne, glad you like.

I'm afraid I cannot reproduce this.

I tried the following todos:
```
Dies ist ein Todo @das_übliche 
Dies ist auch ein Todo @zuHause
```

Then filtered on @das_übliche e.g. http://todo.martinsgill.co.uk/?filter=%40das_%C3%BCbliche and it works correctly, showing only the one item.

Could you please provide an example of something that doesn't work for you. Could you also please let me know the Operating System and Browser you are using, in case it's something specific to one of those.

**Comment by jannehukka** [comment]
Hi,

and thanks for your quick response.

Here are a few examples:

tämä on todo @kynällä
tämä on toinen todo +päivällä
tämä on kolmas todo @yöllä

All the words are searchable but the contexts and projects do not turn into
clickable links. I get the same response as you did with @das_übliche.

I've used the program on OS Yosemite and iOS, browsers have mainly been the
most up-to-date Firefox and Chrome.

Thanks again!

J.




keskiviikko 14. tammikuuta 2015 Martin Gill <notifications@github.com>
kirjoitti:

**Comment by jannehukka** [comment]
Amazing, that's perfect, thanks a lot.

For what it's worth, TodoTxtJs is simply the best todo.txt implementation
that I've tried. The only thing I'm missing is alphabetic sorting of the
list.

But again, great work!

Best wishes,

Janne


lauantai 31. tammikuuta 2015 Martin Gill <notifications@github.com>
kirjoitti:
